package com.sedooj.arch
object Routes {
    const val SIGN_IN = "SIGN_IN"
    const val SIGN_IN_CONFIRMATION = "SIGN_IN_CONFIRMATION"
    const val SIGN_UP = "SIGN_UP"
    const val HOME = "HOME"
    const val MY_RESUMES = "MY_RESUMES"
    const val PROFILE = "PROFILE"
    const val CREATE_RESUME = "CREATE_RESUME"
    const val CREATE_RESUME_VACANCY = "CREATE_RESUME_VACANCY"
    const val CREATE_RESUME_PERSONAL_MAIN = "CREATE_RESUME_PERSONAL_MAIN"
    const val CREATE_RESUME_PERSONAL_SECONDARY = "CREATE_RESUME_PERSONAL_SECONDARY"
    const val CREATE_RESUME_WORK = "CREATE_RESUME_WORK"
    const val CREATE_RESUME_SKILLS = "CREATE_RESUME_SKILLS"
    const val EDUCATION = "EDUCATION"
    const val EDUCATION_EDITOR = "EDUCATION_EDITOR"
}